version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    depends_on:
      - redis
